### ISSUE TITLE
[Tracking issue] Listing deletion endpoint support

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#481]
# Implementation status
- [x] [Dalamud5](https://github.com/goatcorp/Dalamud/pull/377)
- [x] [Dalamud API3](https://github.com/goatcorp/Dalamud/pull/441)
- [ ] [Teamcraft](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/1848)
- [ ] [Universalis ACT Plugin](https://github.com/goaaats/universalis_act_plugin/issues/35)
- [ ] Matcha

This issue will be closed when all clients support the new functionality.
